### PR TITLE
added a java program for finding factorial of a number

### PR DESCRIPTION
**Pull request by therajkuwar**

### CODE REVIEW

**Comment by sherigar** [comment]
rise pr on october 1 else its invalid

**Comment by therajkuwar** [comment]
Okay

**Comment by therajkuwar** [comment]
okay thank you!!

**Comment by therajkuwar** [comment]
> rise pr on october 1 else its invalid



> rise pr on october 1 else its invalid

why my PR's got marked as spam? I got an email of disqualification. Can you do something?

**Pull request closed without merging**
